package com.appnotresponding.rumbo.ui.components.atoms

// RECIEVE A TEXT AND A PLACEHOLDER AND DISPLAY IT IN A TEXT FIELD
// ALSO RECIEVE A BOOLEAN TO KNOW IF THE TEXT FIELD IS ENABLED OR NOT
// AND A REGEX TO VALIDATE THE TEXT FIELD