package com.appnotresponding.rumbo.ui.theme

import androidx.compose.ui.graphics.Color

// ============================================================
// LIGHT SCHEME — Default contrast
// ============================================================
// Key contrast ratios (WCAG AA ≥ 4.5:1 text, ≥ 3:1 UI):
//   primary #4A6800 on surface #F9F9F9 → ~5.1:1 ✓
//   onPrimary #FFFFFF on primary #4A6800 → ~5.1:1 ✓
//   onPrimaryContainer #1A2100 on primaryContainer #D2FF6E → ~12.5:1 ✓
//   onBackground #1E1E1E on background #F9F9F9 → ~15.4:1 ✓
//   onSurfaceVariant #444748 on surfaceVariant #E6E7E8 → ~7.1:1 ✓
//   outline #747878 on surface #F9F9F9 → ~4.5:1 ✓
//   error #BA1A1A on surface #F9F9F9 → ~5.9:1 ✓

val primaryLight = Color(0xFF4A6800)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD2FF6E)
val onPrimaryContainerLight = Color(0xFF1A2100)
val secondaryLight = Color(0xFF5C5F60)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE6E7E8)
val onSecondaryContainerLight = Color(0xFF3B3E3F)
val tertiaryLight = Color(0xFF3B6600)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBDF522)
val onTertiaryContainerLight = Color(0xFF122000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9F9)
val onBackgroundLight = Color(0xFF1E1E1E)
val surfaceLight = Color(0xFFF9F9F9)
val onSurfaceLight = Color(0xFF1E1E1E)
val surfaceVariantLight = Color(0xFFE6E7E8)
val onSurfaceVariantLight = Color(0xFF444748)
val outlineLight = Color(0xFF747878)
val outlineVariantLight = Color(0xFFB3B4B4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313131)
val inverseOnSurfaceLight = Color(0xFFF1F1F1)
val inversePrimaryLight = Color(0xFFBDF522)
val surfaceDimLight = Color(0xFFDADADA)
val surfaceBrightLight = Color(0xFFF9F9F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3F3)
val surfaceContainerLight = Color(0xFFEDEDED)
val surfaceContainerHighLight = Color(0xFFE6E7E8)
val surfaceContainerHighestLight = Color(0xFFDFE0E0)

// ============================================================
// LIGHT SCHEME — Medium contrast
// ============================================================
val primaryLightMediumContrast = Color(0xFF2E4000)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF587700)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF343738)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6B6D6E)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF264800)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4A7A00)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9F9)
val onBackgroundLightMediumContrast = Color(0xFF1E1E1E)
val surfaceLightMediumContrast = Color(0xFFF9F9F9)
val onSurfaceLightMediumContrast = Color(0xFF111111)
val surfaceVariantLightMediumContrast = Color(0xFFE6E7E8)
val onSurfaceVariantLightMediumContrast = Color(0xFF333737)
val outlineLightMediumContrast = Color(0xFF505354)
val outlineVariantLightMediumContrast = Color(0xFF6A6E6E)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313131)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF1F1F1)
val inversePrimaryLightMediumContrast = Color(0xFFBDF522)
val surfaceDimLightMediumContrast = Color(0xFFC9C9C9)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9F9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3F3)
val surfaceContainerLightMediumContrast = Color(0xFFE6E7E8)
val surfaceContainerHighLightMediumContrast = Color(0xFFDADADA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD0D0D0)

// ============================================================
// LIGHT SCHEME — High contrast
// ============================================================
val primaryLightHighContrast = Color(0xFF1A2800)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF3B5000)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2A2C2E)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF47494B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF122000)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2E4C00)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9F9)
val onBackgroundLightHighContrast = Color(0xFF000000)
val surfaceLightHighContrast = Color(0xFFF9F9F9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE6E7E8)
val onSurfaceVariantLightHighContrast = Color(0xFF1E2121)
val outlineLightHighContrast = Color(0xFF292D2D)
val outlineVariantLightHighContrast = Color(0xFF464A4A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313131)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFBDF522)
val surfaceDimLightHighContrast = Color(0xFFBBBBBB)
val surfaceBrightLightHighContrast = Color(0xFFF9F9F9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF1F1F1)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E2)
val surfaceContainerHighLightHighContrast = Color(0xFFD4D4D4)
val surfaceContainerHighestLightHighContrast = Color(0xFFC6C6C6)

// ============================================================
// DARK SCHEME — Default contrast
// ============================================================
// Key contrast ratios (WCAG AA ≥ 4.5:1 text, ≥ 3:1 UI):
//   primary #BDF522 on surface #1E1E1E → ~11.8:1 ✓
//   onPrimary #263500 on primary #BDF522 → ~5.2:1 ✓
//   onPrimaryContainer #D2FF6E on primaryContainer #3A5000 → ~6.3:1 ✓
//   onBackground #E6E7E8 on background #1E1E1E → ~12.1:1 ✓
//   onSurfaceVariant #C4C7C7 on surfaceVariant #444748 → ~5.6:1 ✓
//   outline #8E9192 on surface #1E1E1E → ~4.7:1 ✓
//   error #FFB4AB on surface #1E1E1E → ~8.5:1 ✓

val primaryDark = Color(0xFFBDF522)
val onPrimaryDark = Color(0xFF263500)
val primaryContainerDark = Color(0xFF3A5000)
val onPrimaryContainerDark = Color(0xFFD2FF6E)
val secondaryDark = Color(0xFFE6E7E8)
val onSecondaryDark = Color(0xFF2E3132)
val secondaryContainerDark = Color(0xFF444748)
val onSecondaryContainerDark = Color(0xFFE6E7E8)
val tertiaryDark = Color(0xFFBDF522)
val onTertiaryDark = Color(0xFF1A2E00)
val tertiaryContainerDark = Color(0xFF2E4800)
val onTertiaryContainerDark = Color(0xFFD2FF6E)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1E1E1E)
val onBackgroundDark = Color(0xFFE6E7E8)
val surfaceDark = Color(0xFF1E1E1E)
val onSurfaceDark = Color(0xFFE6E7E8)
val surfaceVariantDark = Color(0xFF444748)
val onSurfaceVariantDark = Color(0xFFC4C7C7)
val outlineDark = Color(0xFF8E9192)
val outlineVariantDark = Color(0xFF444748)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E7E8)
val inverseOnSurfaceDark = Color(0xFF313131)
val inversePrimaryDark = Color(0xFF4A6800)
val surfaceDimDark = Color(0xFF1E1E1E)
val surfaceBrightDark = Color(0xFF3A3A3A)
val surfaceContainerLowestDark = Color(0xFF141414)
val surfaceContainerLowDark = Color(0xFF262626)
val surfaceContainerDark = Color(0xFF2C2C2C)
val surfaceContainerHighDark = Color(0xFF333333)
val surfaceContainerHighestDark = Color(0xFF3A3A3A)

// ============================================================
// DARK SCHEME — Medium contrast
// ============================================================
val primaryDarkMediumContrast = Color(0xFFCDFF5A)
val onPrimaryDarkMediumContrast = Color(0xFF1A2800)
val primaryContainerDarkMediumContrast = Color(0xFF8ABB00)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFF0F1F2)
val onSecondaryDarkMediumContrast = Color(0xFF232627)
val secondaryContainerDarkMediumContrast = Color(0xFF8E9191)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFCDFF5A)
val onTertiaryDarkMediumContrast = Color(0xFF0E1900)
val tertiaryContainerDarkMediumContrast = Color(0xFF8ABB00)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF1E1E1E)
val onBackgroundDarkMediumContrast = Color(0xFFE6E7E8)
val surfaceDarkMediumContrast = Color(0xFF1E1E1E)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF444748)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDADDDD)
val outlineDarkMediumContrast = Color(0xFFAFB2B3)
val outlineVariantDarkMediumContrast = Color(0xFF8E9191)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE6E7E8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2B2B2B)
val inversePrimaryDarkMediumContrast = Color(0xFF3A5000)
val surfaceDimDarkMediumContrast = Color(0xFF1E1E1E)
val surfaceBrightDarkMediumContrast = Color(0xFF454545)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0E0E0E)
val surfaceContainerLowDarkMediumContrast = Color(0xFF262626)
val surfaceContainerDarkMediumContrast = Color(0xFF303030)
val surfaceContainerHighDarkMediumContrast = Color(0xFF3B3B3B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF464646)

// ============================================================
// DARK SCHEME — High contrast
// ============================================================
val primaryDarkHighContrast = Color(0xFFE2FF9E)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBDF522)
val onPrimaryContainerDarkHighContrast = Color(0xFF0D1500)
val secondaryDarkHighContrast = Color(0xFFFFFFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFE6E7E8)
val onSecondaryContainerDarkHighContrast = Color(0xFF1A1C1D)
val tertiaryDarkHighContrast = Color(0xFFE2FF9E)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBDF522)
val onTertiaryContainerDarkHighContrast = Color(0xFF0A1200)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF1E1E1E)
val onBackgroundDarkHighContrast = Color(0xFFFFFFFF)
val surfaceDarkHighContrast = Color(0xFF1E1E1E)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF444748)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEF0F1)
val outlineVariantDarkHighContrast = Color(0xFFC0C3C3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE6E7E8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2E4000)
val surfaceDimDarkHighContrast = Color(0xFF1E1E1E)
val surfaceBrightDarkHighContrast = Color(0xFF515151)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF262626)
val surfaceContainerDarkHighContrast = Color(0xFF353535)
val surfaceContainerHighDarkHighContrast = Color(0xFF414141)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4D4D4D)

